# Change these first
# Your GitHub organization or username, where this repository lives
owner: ahoraficho

# The name of this repository
repo: ahoraficho-status
# user-agent: ahoraficho-status
sites:

  - name: Demo AhoraFicho.es
    url: https://demoplanbasico.ahoraficho.es
    # type: globalping
    # location: u-Solutions2AZ:ahoraficho-00
    expectedStatusCodes:
      - 200
      - 0

  - name: Demo Completa AhoraFicho.es
    url: https://democompleta.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: Polaris
    url: https://intranet.polaris.es
    expectedStatusCodes:
      - 200
      - 0

  - name: Armanext
    url: https://intranet.armanext.com
    expectedStatusCodes:
      - 200
      - 0

  - name: Fundacion Del Valle
    url: https://intranet.fundaciondelvalle.org
    expectedStatusCodes:
      - 200
      - 0

  - name: NextAbogados
    url: https://intranet.nextabogados.com
    expectedStatusCodes:
      - 200
      - 0

  - name: Silon Aviación
    url: https://silonaviacion.wm2az.solutions2az.net
    expectedStatusCodes:
      - 200
      - 0

  - name: ENJ Consultores
    url: https://intranet.enjconsultores.es
    expectedStatusCodes:
      - 200
      - 0
      
  - name: Imagetours
    url: https://intranet.imagetours.es
    expectedStatusCodes:
      - 200
      - 0
      
  - name: Inelter Casar
    url: https://ineltercasar.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: LT Estilistas
    url: https://ltestilistas.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0
  - name: Interactive Club
    url: https://interactiveclub.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0
  - name: Escolactiva Lugo
    url: https://escolactivalugo.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0
      
  - name: SGD Me Cuida
    url: https://sgdmecuida.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0
      
  - name: Alfalfa Spain
    url: https://alfalfaspain.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: Ad-Lante Marketing
    url: https://ad-lante.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: Barracuda YD
    url: https://barracuda-yd.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: Arsai Guarderia
    url: https://arsaiguarderia.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: Theming Profile
    url: https://theming.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: S2PI Servicios de Prevención
    url: https://s2pi.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: Perez Cardoso
    url: https://perezcardoso.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: Eletur Ascensores
    url: https://eletur.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: Agribripe
    url: https://agribripe.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: FHM Instalaciones
    url: https://fmh-instalaciones.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: Instituto Internacional Puerto Real
    url: https://instituto-internacional-puertoreal.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0
  - name: Demo Carhaus
    url: https://democarhaus.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0
  - name: IPEC Centro
    url: https://ipeccentro.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0
  - name: Arboristas del Sur
    url: https://arboristasdelsur.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0
  - name: Campo de Gibraltar
    url: https://campodegibraltar.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: Taller Sanchez Ibañez
    url: https://tallersanchezibanez.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: Guts and Love
    url: https://gutsandlove.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0
  - name: Tila Bakes Pasteleria
    url: https://tilabakes.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: Peral Carpinteros
    url: https://peralcarpinteros.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: Antares Imagen
    url: https://antaresimagen.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: Crisalferro
    url: https://crisalferro.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: Construccion Sanchez Ruiz
    url: https://construccionessanchezruiz.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: Urbanización Puig Val
    url: https://urbanizacion-puig-val.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: Carlin 50008
    url: https://carlin50008.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: Cafeteria Belsot
    url: https://cafeteria-belsot.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

  - name: Venijunes Carrefour Express
    url: https://venijunes.ahoraficho.es
    expectedStatusCodes:
      - 200
      - 0

status-website:
  # theme: ligth
  # theme: dark
  # theme: night
  theme: ocean

  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ahoraficho.es
  # baseUrl: /workermanager2az-status

  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: AhoraFicho - Status Page

  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:

    - title: Status
      href: /

    - title: Solutions2AZ
      href: https://www.solutions2az.net

    - title: AhoraFicho
      href: https://www.ahoraficho.es

  metaTags:
    - name: "robots"
      content: "noindex"

# Issues are automatically closed once they are resolved, however if they are open for less 
# than 15 minutes they are deleted instead.
skipDeleteIssues: true

# The syntax followed is that of cron.
workflowSchedule:
  graphs: "0 */2 * * *"
  responseTime: "0 */2 * * *"
  staticSite: "0 */12 * * *"
  summary: "0 */2 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 */1 * * *"
  uptime: "*/5 * * * *"

# Removing the footer
i18n:
  footer: ""

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
